/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EspaceRouteImport } from './routes/espace'
import { Route as EspaceIndexRouteImport } from './routes/espace.index'
import { Route as EspaceAdministrationRouteImport } from './routes/espace.administration'
import { Route as EspaceArchitectureRouteImport } from './routes/espace.architecture'
import { Route as EspacePasseportRouteImport } from './routes/espace.passeport'
import { Route as EspaceProfilRouteImport } from './routes/espace.profil'
import { Route as EspaceRessourcesRouteImport } from './routes/espace.ressources'
import { Route as EspaceStageRouteImport } from './routes/espace.stage'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceRoute = EspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => rootRouteImport,
} as any)
const EspaceIndexRoute = EspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceAdministrationRoute = EspaceAdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceArchitectureRoute = EspaceArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => EspaceRoute,
} as any)
const EspacePasseportRoute = EspacePasseportRouteImport.update({
  id: '/passeport',
  path: '/passeport',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceProfilRoute = EspaceProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceRessourcesRoute = EspaceRessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => EspaceRoute,
} as any)
const EspaceStageRoute = EspaceStageRouteImport.update({
  id: '/stage',
  path: '/stage',
  getParentRoute: () => EspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/espace': typeof EspaceRouteWithChildren
  '/espace/administration': typeof EspaceAdministrationRoute
  '/espace/architecture': typeof EspaceArchitectureRoute
  '/espace/passeport': typeof EspacePasseportRoute
  '/espace/profil': typeof EspaceProfilRoute
  '/espace/ressources': typeof EspaceRessourcesRoute
  '/espace/stage': typeof EspaceStageRoute
  '/espace/': typeof EspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/espace/administration': typeof EspaceAdministrationRoute
  '/espace/architecture': typeof EspaceArchitectureRoute
  '/espace/passeport': typeof EspacePasseportRoute
  '/espace/profil': typeof EspaceProfilRoute
  '/espace/ressources': typeof EspaceRessourcesRoute
  '/espace/stage': typeof EspaceStageRoute
  '/espace': typeof EspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/espace': typeof EspaceRouteWithChildren
  '/espace/administration': typeof EspaceAdministrationRoute
  '/espace/architecture': typeof EspaceArchitectureRoute
  '/espace/passeport': typeof EspacePasseportRoute
  '/espace/profil': typeof EspaceProfilRoute
  '/espace/ressources': typeof EspaceRessourcesRoute
  '/espace/stage': typeof EspaceStageRoute
  '/espace/': typeof EspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/espace'
    | '/espace/administration'
    | '/espace/architecture'
    | '/espace/passeport'
    | '/espace/profil'
    | '/espace/ressources'
    | '/espace/stage'
    | '/espace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/espace/administration'
    | '/espace/architecture'
    | '/espace/passeport'
    | '/espace/profil'
    | '/espace/ressources'
    | '/espace/stage'
    | '/espace'
  id:
    | '__root__'
    | '/'
    | '/espace'
    | '/espace/administration'
    | '/espace/architecture'
    | '/espace/passeport'
    | '/espace/profil'
    | '/espace/ressources'
    | '/espace/stage'
    | '/espace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EspaceRoute: typeof EspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace': {
      id: '/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof EspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espace/': {
      id: '/espace/'
      path: '/'
      fullPath: '/espace/'
      preLoaderRoute: typeof EspaceIndexRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/administration': {
      id: '/espace/administration'
      path: '/administration'
      fullPath: '/espace/administration'
      preLoaderRoute: typeof EspaceAdministrationRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/architecture': {
      id: '/espace/architecture'
      path: '/architecture'
      fullPath: '/espace/architecture'
      preLoaderRoute: typeof EspaceArchitectureRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/passeport': {
      id: '/espace/passeport'
      path: '/passeport'
      fullPath: '/espace/passeport'
      preLoaderRoute: typeof EspacePasseportRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/profil': {
      id: '/espace/profil'
      path: '/profil'
      fullPath: '/espace/profil'
      preLoaderRoute: typeof EspaceProfilRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/ressources': {
      id: '/espace/ressources'
      path: '/ressources'
      fullPath: '/espace/ressources'
      preLoaderRoute: typeof EspaceRessourcesRouteImport
      parentRoute: typeof EspaceRoute
    }
    '/espace/stage': {
      id: '/espace/stage'
      path: '/stage'
      fullPath: '/espace/stage'
      preLoaderRoute: typeof EspaceStageRouteImport
      parentRoute: typeof EspaceRoute
    }
  }
}

interface EspaceRouteChildren {
  EspaceAdministrationRoute: typeof EspaceAdministrationRoute
  EspaceArchitectureRoute: typeof EspaceArchitectureRoute
  EspacePasseportRoute: typeof EspacePasseportRoute
  EspaceProfilRoute: typeof EspaceProfilRoute
  EspaceRessourcesRoute: typeof EspaceRessourcesRoute
  EspaceStageRoute: typeof EspaceStageRoute
  EspaceIndexRoute: typeof EspaceIndexRoute
}

const EspaceRouteChildren: EspaceRouteChildren = {
  EspaceAdministrationRoute: EspaceAdministrationRoute,
  EspaceArchitectureRoute: EspaceArchitectureRoute,
  EspacePasseportRoute: EspacePasseportRoute,
  EspaceProfilRoute: EspaceProfilRoute,
  EspaceRessourcesRoute: EspaceRessourcesRoute,
  EspaceStageRoute: EspaceStageRoute,
  EspaceIndexRoute: EspaceIndexRoute,
}

const EspaceRouteWithChildren =
  EspaceRoute._addFileChildren(EspaceRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EspaceRoute: EspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
